language: java
install: "./gradlew setupCIWorkspace"
script: "./gradlew jar"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: s3
  access_key_id: AKIAJD52NMRJM5EIGQZQ
  secret_access_key:
    secure: fUlPpLgnJ3rXW6mcTx+NMCFkepb2dc0t7x68f4PysMq6p0MK61L1brONyQdqTVYdphhevBuW/aot7vK9sWOjhexEfu6M0yFv8am57W16hgyD+8CuPX9NheVjTK4nfcddFap/ax5+1Hs3OKQnomRZcFc87buCvoQ0rNwBPibhxHglZhddX3ZCFJ4OQuCMVNoy7JVozeJoqTEsPV7n4bW11L71v7oTreWRjaUizqB144FKGSkGDY/FIkZuYA75yQrJgGVdGg0f0n4pJMLySAvTCH8Po6pXrIjmXJdC2y+SpriNoL8JZKB/40CG6b6wlOnsbO1trsA0vw7xxwFr1MB08Ze5OrrEpiXc9dBQyjdolvQEuwbpWhW6FRWYYjJ18NEp5pMJBqcI+FJTO27+mGboHOjncLWkzt+h3Ty3P4j6bicWXwmH/ujXPaMsgjRM+7jP2Wo23dmjYfgwGUyS3pA5tfm/9plSfFK9jriezaI6A6F0F13tAkFYTpwEK0xnzSZqs5BBx2hhTuG+svmZKxZBepIZ+NxexFvgyRNqMZrYFZAcgXBXXZdM2/r7rREyl502Avh56XQJbt7jYLwHqx1x2qX56DlYtKG1idoQcaoMIhIkjYe4FwuyFpY6jFVL7iJxdJtYWOAbqnGRVpejROmJfFDZhWzVRIMPbV4e7M0KH8M=
  bucket: travis.teamrtg.org
  local-dir: build/libs/
  upload-dir: RTG-1.8.9
  skip_cleanup: true
  acl: public_read
  region: ap-southeast-2
