language: java
jdk:
  - oraclejdk8
install: "./gradlew setupCIWorkspace"
script: "./gradlew build"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: s3
  access_key_id: AKIAIZ4H7ETBDX4MY3TA
  secret_access_key:
    secure: tbwEvUFbJAZmWt8clRcaZ4HJcqauMLvD+gP1hKYn3/gXyLdsyaKoAX5qfSyMLCw9QMxIaXLr9Pqn1xzl2qSz/VHm3o0P2nyQu1pccZi96o3shGaIqPuLMfMpksfMCAICvG4fiTcIoFR7Iqkb61TFu/mpB0BK92CL+uTwK3B32oTGBE4BKu3qOeeNjiCUwgtwY/ZiOqjK93mzlMFkzJZ0fHXltK5gT2wnhyXlVvv//82ByLe1NMG+l8Aedn2SY6yH/wcILl2biPOLZiGOx2TA9mib5jG7+W/JBcTdwj8lKr3cnniWy1vA38s5ZCowtd9YGbouHYENz42MDUkOMm0PWSVRGZvPm8bhTg1OeHZ9ebuyXf4Qt1j06pCCiuOq+8RhRHZifCzR2kAiIFUg2hmhdkFCNMtJquNFuYn9obY8Fe9HPsYymi7P6F5SKTHr9PyFhwjw2yNNtoerrthY+lP12qNfLnVPzJdhQVYIChDVXph+Y1vcKT5NIcDFoH2UXvGpapQvSWuxFFMEJFLw/fxtcf5eiL+isuVZv+r76QESvDLOPZi9UiCFzKOkNESzzZgo92a0uKTBJJQEDMND3s0RB9blxqc1tG9xixopuJroAyUmnfOGLOp37zunWojs1B6YGnRv4aDct8dBPWUhH6FrceCDr+Xp6n36XBRz+dxSvmU=
  bucket: travis.teamrtg.org
  local-dir: build/libs/
  upload-dir: RTG-1.9
  skip_cleanup: true
  acl: public_read
  region: ap-southeast-2
  on:
    repo: Team-RTG/1.9-Realistic-Terrain-Generation
    all_branches: true